### PR TITLE
Make LDAP client-side TLS authentication optional

### PR DESCRIPTION
**Pull request by sabo**
Adds a configuration option `client_tls` to `sssd::provider::ldap` that, when set to false, lets SSSD LDAP providers be configured without setting client-side TLS certificate and key options.

### CODE REVIEW

**Comment by sabo** [comment]
Is there a chance that this could be reviewed sometime soon?

**Review by op-ct — COMMENTED** [review]
Hi @sabo, thanks for the contribution!  

Sorry for the delay on merging―it's likely because there were no tests to accompany this change in behavior, and it might be a while before the maintainers can get around to adding them.  

If you're interested in accelerating the release of this patch: a contribution of tests would be gladly accepted!

**Comment by sabo** [comment]
tests added

**Comment by virus2500** [comment]
Hi, 

since @sabo added tests could it be reviewed now? Pretty please :)

**Comment by sabo** [comment]
@op-ct re-upping this, is the review for this PR waiting on anything else on my end?

**Comment by sabo** [comment]
We're at a year and a few months of this PR being open, can it please be reviewed? Or, if it's not going to be merged, can it be closed?

**Comment by DennisPohlmann** [comment]
@op-ct Please review this MR, client-side TLS authentication should be optional!

**Review by DennisPohlmann — APPROVED** [review]
client-side TLS authentication

**Comment by DennisPohlmann** [comment]
@aaronlippold Please have a look

**Review by aaronlippold — COMMENTED** [review]
Looks good

**Pull request merged**
