### PR TITLE
(SIMP-2971) Add $simp_options::package_ensure

### PR DESCRIPTION
**Pull request by jeefberkey**
- Changed $sssd::install::package_ensure from 'latest' to 'installed'
  - It will also respect `simp_options::package_ensure`

SIMP-2971 #comment update sssd

### CODE REVIEW

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-sssd/pipelines/33044890

**Comment by lnemsick-simp** [comment]
ad test is failing because the new logic in simp-beaker-helpers wrt ssh pre-population of /etc/ssh/local_keys/  is trying to execute linux operations on a windows box?  Seems like a bug in this new capability.  Should be confined to OSes where it makes sense.

**Comment by jeefberkey** [comment]
The AD suite is passing here: https://gitlab.com/simp/pupmod-simp-sssd/pipelines/33472973 with my beaker-helpers changes. Those will go up soon, but I will remove it from the gemfile for now.

**Comment by jeefberkey** [comment]
beaker-helpers PR https://github.com/simp/rubygem-simp-beaker-helpers/pull/84

**Pull request merged**
